{ statuses:
   [ { created_at: 'Thu Mar 29 02:44:21 +0000 2018',
       id: 979187474625777700,
       id_str: '979187474625777665',
       full_text: 'RT @camillekostek: Vote baby vote. I’m ready to get to work and come back as one of your @SI_Swimsuit rookies for the 2019 class 👙🕺🏼 https:…',
       truncated: false,
       display_text_range: [Array],
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 43,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       lang: 'en' },
     { created_at: 'Thu Mar 29 02:43:47 +0000 2018',
       id: 979187334099996700,
       id_str: '979187334099996674',
       full_text: 'A red swimsuit from a Canadian brand? Ruby Red from SHAN is the to-die-for red you’ve been searching for, an exclusive limited edition. This one-shoulder designer swimsuit transforms your shoulders into a frame worthy of a goddess.\nhttps://t.co/FMdDKqhvft https://t.co/gF21gPYXdd',
       truncated: false,
       display_text_range: [Array],
       entities: [Object],
       extended_entities: [Object],
       metadata: [Object],
       source: '<a href="http://gainapp.com" rel="nofollow">Gain App</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Thu Mar 29 02:43:08 +0000 2018',
       id: 979187170559787000,
       id_str: '979187170559787008',
       full_text: 'RT @fashion_youtube: Samantha Hoopes Intimates Swimsuit 2018 | Sports Illustrated Swimsuit HD https://t.co/4boHvGbDb8 vía @YouTube',
       truncated: false,
       display_text_range: [Array],
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 1,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Thu Mar 29 02:42:29 +0000 2018',
       id: 979187005413314600,
       id_str: '979187005413314561',
       full_text: 'RT @SI_Swimsuit: Watch as @BarbaraPalvin searches for the perfect swimsuit. https://t.co/pz0t3sstxb',
       truncated: false,
       display_text_range: [Array],
       entities: [Object],
       extended_entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 85,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Thu Mar 29 02:42:13 +0000 2018',
       id: 979186939155943400,
       id_str: '979186939155943426',
       full_text: 'I just entered @albionfit’s Spring Break Swimsuit Giveaway!! You should too! https://t.co/MEXBcYdgIf',
       truncated: false,
       display_text_range: [Array],
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Thu Mar 29 02:41:54 +0000 2018',
       id: 979186859795415000,
       id_str: '979186859795415040',
       full_text: 'I miss wearing just a swimsuit and ‘ie. Alaska be too cold for that kinda outfit☹️',
       truncated: false,
       display_text_range: [Array],
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       lang: 'en' },
     { created_at: 'Thu Mar 29 02:41:32 +0000 2018',
       id: 979186769378725900,
       id_str: '979186769378725888',
       full_text: 'RT @LornajaneCosign: Newly Listed ~  Penbrooke Women\'s Plus-Size One Piece Teal Blue Emerald Green Swimsuit Size 18W  #SwimWear #Shopping #…',
       truncated: false,
       display_text_range: [Array],
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 7,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Thu Mar 29 02:41:20 +0000 2018',
       id: 979186715649654800,
       id_str: '979186715649654784',
       full_text: '@RonHoran Swimsuit ulul hahahahaha',
       truncated: false,
       display_text_range: [Array],
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: 978846896314830800,
       in_reply_to_status_id_str: '978846896314830848',
       in_reply_to_user_id: 2309258718,
       in_reply_to_user_id_str: '2309258718',
       in_reply_to_screen_name: 'RonHoran',
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       lang: 'tl' },
     { created_at: 'Thu Mar 29 02:41:17 +0000 2018',
       id: 979186706883559400,
       id_str: '979186706883559426',
       full_text: 'RT @MoRoRadio: If this gets 500 #RTs @DustinALTAZ will wear a Borat swimsuit to @altaz933\'s #BandSplash 🌊🎸🏄‍♀️🥁🌊 https://t.co/CdGOuqnVov',
       truncated: false,
       display_text_range: [Array],
       entities: [Object],
       extended_entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 34,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Thu Mar 29 02:40:50 +0000 2018',
       id: 979186590680535000,
       id_str: '979186590680535040',
       full_text: 'RT @ThePINKlilypad: #TuesdayThoughts Swimsuit girls #retrostickers #retrogirls #pinupgirls #glam #makeup #beauty #gifts #shop #shopping #sh…',
       truncated: false,
       display_text_range: [Array],
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 1,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       lang: 'en' } ],
  search_metadata:
   { completed_in: 0.072,
     max_id: 979187474625777700,
     max_id_str: '979187474625777665',
     next_results: '?max_id=979186590680535039&q=%22swimsuit%22&count=10&include_entities=1',
     query: '%22swimsuit%22',
     refresh_url: '?since_id=979187474625777665&q=%22swimsuit%22&include_entities=1',
     count: 10,
     since_id: 0,
     since_id_str: '0' } }